/* PWR Golf Co. inventory — every used club is one physical item with one SKU. When it sells in-store, mark it sold in /admin and it disappears everywhere. */
window.PWR_DATA = {
 "generated": "2026-09-09",
 "cond": {
  "10": [
   "Brand New",
   "Unused, in original packaging."
  ],
  "9.5": [
   "Mint",
   "Hit a handful of times at most. No marks worth mentioning."
  ],
  "9": [
   "Excellent",
   "Light use. Faint bag chatter only under close inspection."
  ],
  "8": [
   "Very Good",
   "Normal play wear. Some sole scuffs, no dents or sky marks."
  ],
  "7": [
   "Good",
   "Honest wear. Visible sole/face scratches, maybe a small crown mark. Plays perfectly."
  ],
  "6": [
   "Fair",
   "Well-used. Cosmetic issues we photograph and describe. Priced accordingly."
  ]
 },
 "cats": [
  [
   "driver",
   "Drivers"
  ],
  [
   "wood",
   "Fairway Woods"
  ],
  [
   "hybrid",
   "Hybrids"
  ],
  [
   "iron",
   "Iron Sets"
  ],
  [
   "wedge",
   "Wedges"
  ],
  [
   "putter",
   "Putters"
  ],
  [
   "set",
   "Complete Sets"
  ],
  [
   "shaft",
   "Shafts"
  ],
  [
   "grip",
   "Grips"
  ],
  [
   "ball",
   "Golf Balls"
  ],
  [
   "bag",
   "Bags"
  ],
  [
   "glove",
   "Gloves"
  ],
  [
   "accessory",
   "Accessories"
  ],
  [
   "apparel",
   "Apparel"
  ]
 ],
 "brands": [
  [
   "Titleist",
   "Drivers, woods, hybrids, irons, Vokey wedges, Scotty Cameron putters, Pro V1."
  ],
  [
   "TaylorMade",
   "Qi35, P-Series irons, MG wedges, Spider putters, TP5."
  ],
  [
   "Callaway",
   "Elyte, Apex, Jaws wedges, Odyssey putters, Chrome Tour."
  ],
  [
   "Ping",
   "G440, i240, Blueprint, s159 wedges, PLD putters, Hoofer bags."
  ],
  [
   "Cobra",
   "DS-ADAPT, King Tour irons, Snakebite wedges."
  ],
  [
   "Mizuno",
   "JPX 925, Pro 24x series, T24 wedges."
  ],
  [
   "Srixon",
   "ZXi drivers and irons, Z-Star."
  ],
  [
   "Cleveland",
   "RTX ZipCore wedges, Frontline putters, Halo XL."
  ],
  [
   "Odyssey",
   "Ai-One, Jailbird, White Hot, Tri-Hot."
  ],
  [
   "Scotty Cameron",
   "Studio Style, Phantom, Special Select. New and pre-owned."
  ],
  [
   "Vokey",
   "SM10 and WedgeWorks, all grinds in stock."
  ],
  [
   "PXG",
   "0311 GEN7, Black Ops. Pre-owned mostly, some new."
  ],
  [
   "Fujikura",
   "Ventus (real VeloCore), Speeder NX, Motore X."
  ],
  [
   "Graphite Design",
   "Tour AD DI, IZ, VF, XC, UB."
  ],
  [
   "Project X",
   "HZRDUS, Denali, Cypher, Project X / LZ / IO iron shafts."
  ],
  [
   "KBS",
   "Tour, $-Taper, Tour Lite, TGI, CT Tour putter shafts."
  ],
  [
   "Mitsubishi",
   "Tensei 1K, Diamana, Kai'li, MMT."
  ],
  [
   "True Temper",
   "Dynamic Gold, AMT, Elevate."
  ],
  [
   "Nippon",
   "Modus3, N.S. Pro, Zelos."
  ],
  [
   "Golf Pride",
   "MCC, Tour Velvet, CP2, Z-Grip, Align."
  ],
  [
   "SuperStroke",
   "Zenergy, Traxion, Pistol, S-Tech."
  ],
  [
   "Lamkin",
   "Crossline, Sonar, UTx."
  ],
  [
   "Vessel",
   "Player IV, VLS Lux, Sunday III."
  ],
  [
   "Sun Mountain",
   "C-130, 4.5 LS, Sync."
  ],
  [
   "FootJoy",
   "Gloves and shoes."
  ],
  [
   "Bushnell",
   "Tour V6, Pro X3, Wingman."
  ],
  [
   "Garmin",
   "Approach S70, R10 launch monitor."
  ],
  [
   "Bridgestone",
   "Tour B series."
  ]
 ],
 "used": [
  {
   "sku": "PWR-TM-STEALT-DRIVER-00101",
   "brand": "TaylorMade",
   "model": "Stealth 2",
   "cat": "driver",
   "club": "Driver",
   "price": 149,
   "cond": 7,
   "type": "used",
   "dex": "RH",
   "flex": "Stiff",
   "loft": "9\u00b0",
   "shaftBrand": "Fujikura",
   "shaftModel": "Ventus Red 5",
   "length": "45.5\"",
   "lie": "Standard",
   "setComp": null,
   "gripCond": "Fair",
   "grip": "Golf Pride Tour Velvet",
   "headcover": true,
   "serial": null,
   "notes": "Small sky mark on crown near heel, otherwise clean. Face and sole show normal wear. This one is priced to move.",
   "tradeEligible": true,
   "arrived": "2026-09-08",
   "find": true,
   "featured": true,
   "compare": 229,
   "year": 2023
  },
  {
   "sku": "PWR-TI-TSR3-DRIVER-00102",
   "brand": "Titleist",
   "model": "TSR3",
   "cat": "driver",
   "club": "Driver",
   "price": 329,
   "cond": 9,
   "type": "used",
   "dex": "RH",
   "flex": "Stiff",
   "loft": "10\u00b0",
   "shaftBrand": "Graphite Design",
   "shaftModel": "Tour AD DI-6",
   "length": "45.25\"",
   "lie": "Standard",
   "setComp": null,
   "gripCond": "Good",
   "grip": "Golf Pride Tour Velvet",
   "headcover": true,
   "serial": "T3R\u20268821",
   "notes": "Excellent shape. Tour AD DI is a $400 shaft on its own. Headcover and wrench included.",
   "tradeEligible": true,
   "arrived": "2026-09-07",
   "find": false,
   "featured": true,
   "compare": null,
   "year": 2023
  },
  {
   "sku": "PWR-CW-PARADY-DRIVER-00103",
   "brand": "Callaway",
   "model": "Paradym Ai Smoke Max",
   "cat": "driver",
   "club": "Driver",
   "price": 309,
   "cond": 9,
   "type": "used",
   "dex": "RH",
   "flex": "Regular",
   "loft": "10.5\u00b0",
   "shaftBrand": "Mitsubishi",
   "shaftModel": "Tensei AV Blue 65",
   "length": "45.75\"",
   "lie": "Standard",
   "setComp": null,
   "gripCond": "Good",
   "grip": "Golf Pride Tour Velvet",
   "headcover": true,
   "serial": null,
   "notes": "Barely played. Owner switched to Ping. Faint bag chatter on the sole.",
   "tradeEligible": true,
   "arrived": "2026-09-06",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2024
  },
  {
   "sku": "PWR-PG-G430MA-DRIVER-00104",
   "brand": "Ping",
   "model": "G430 Max",
   "cat": "driver",
   "club": "Driver",
   "price": 289,
   "cond": 8,
   "type": "used",
   "dex": "RH",
   "flex": "Stiff",
   "loft": "9\u00b0",
   "shaftBrand": "Ping",
   "shaftModel": "Alta CB Black 55",
   "length": "45.25\"",
   "lie": "Standard",
   "setComp": null,
   "gripCond": "Good",
   "grip": "Golf Pride Tour Velvet",
   "headcover": true,
   "serial": null,
   "notes": "Normal play wear. Face is clean. Headcover included.",
   "tradeEligible": true,
   "arrived": "2026-09-03",
   "find": false,
   "featured": true,
   "compare": null,
   "year": 2023
  },
  {
   "sku": "PWR-CB-DARKSP-DRIVER-00105",
   "brand": "Cobra",
   "model": "Darkspeed LS",
   "cat": "driver",
   "club": "Driver",
   "price": 219,
   "cond": 8,
   "type": "used",
   "dex": "RH",
   "flex": "X-Stiff",
   "loft": "9\u00b0",
   "shaftBrand": "Project X",
   "shaftModel": "HZRDUS Black 60",
   "length": "45\"",
   "lie": "Standard",
   "setComp": null,
   "gripCond": "Good",
   "grip": "Golf Pride Tour Velvet",
   "headcover": true,
   "serial": null,
   "notes": "Low-spin head for the faster player. One tiny paint chip on the crown, photographed.",
   "tradeEligible": true,
   "arrived": "2026-09-01",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2024
  },
  {
   "sku": "PWR-TM-QI10MA-DRIVER-00106",
   "brand": "TaylorMade",
   "model": "Qi10 Max",
   "cat": "driver",
   "club": "Driver",
   "price": 279,
   "cond": 8,
   "type": "used",
   "dex": "RH",
   "flex": "Regular",
   "loft": "10.5\u00b0",
   "shaftBrand": "Fujikura",
   "shaftModel": "Speeder NX 50",
   "length": "45.75\"",
   "lie": "Standard",
   "setComp": null,
   "gripCond": "New",
   "grip": "Golf Pride MCC Plus4",
   "headcover": true,
   "serial": null,
   "notes": "Forgiveness monster. Grip is fresh \u2014 we regripped it on arrival.",
   "tradeEligible": true,
   "arrived": "2026-09-05",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2024
  },
  {
   "sku": "PWR-TI-TSI2-DRIVER-00107",
   "brand": "Titleist",
   "model": "TSi2",
   "cat": "driver",
   "club": "Driver",
   "price": 199,
   "cond": 7,
   "type": "used",
   "dex": "RH",
   "flex": "Senior",
   "loft": "11\u00b0",
   "shaftBrand": "Mitsubishi",
   "shaftModel": "Kuro Kage Black 50",
   "length": "45.5\"",
   "lie": "Standard",
   "setComp": null,
   "gripCond": "Good",
   "grip": "Golf Pride Tour Velvet",
   "headcover": true,
   "serial": null,
   "notes": "Senior flex, high launch. Honest wear on the sole, a couple of crown scuffs. Great value.",
   "tradeEligible": true,
   "arrived": "2026-08-25",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2021
  },
  {
   "sku": "PWR-PG-G425LS-DRIVER-00108",
   "brand": "Ping",
   "model": "G425 LST",
   "cat": "driver",
   "club": "Driver",
   "price": 229,
   "cond": 8,
   "type": "used",
   "dex": "LH",
   "flex": "Stiff",
   "loft": "9\u00b0",
   "shaftBrand": "Ping",
   "shaftModel": "Tour 65",
   "length": "45.25\"",
   "lie": "Standard",
   "setComp": null,
   "gripCond": "Good",
   "grip": "Golf Pride Tour Velvet",
   "headcover": true,
   "serial": null,
   "notes": "Left-handed. Rare to find LST heads in LH \u2014 grab it.",
   "tradeEligible": true,
   "arrived": "2026-08-28",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2021
  },
  {
   "sku": "PWR-CW-ROGUES-DRIVER-00109",
   "brand": "Callaway",
   "model": "Rogue ST Max",
   "cat": "driver",
   "club": "Driver",
   "price": 169,
   "cond": 7,
   "type": "used",
   "dex": "RH",
   "flex": "Regular",
   "loft": "10.5\u00b0",
   "shaftBrand": "Project X",
   "shaftModel": "Cypher 50",
   "length": "45\"",
   "lie": "Standard",
   "setComp": null,
   "gripCond": "Good",
   "grip": "Golf Pride Tour Velvet",
   "headcover": false,
   "serial": null,
   "notes": "Small sky mark, otherwise clean. Shaft has been shortened to 45\" \u2014 plays great for a lot of people.",
   "tradeEligible": true,
   "arrived": "2026-08-20",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2022
  },
  {
   "sku": "PWR-TI-TSR2-DRIVER-00110",
   "brand": "Titleist",
   "model": "TSR2",
   "cat": "driver",
   "club": "Driver",
   "price": 299,
   "cond": 9,
   "type": "used",
   "dex": "RH",
   "flex": "Stiff",
   "loft": "9\u00b0",
   "shaftBrand": "Fujikura",
   "shaftModel": "Ventus Blue 6 (VeloCore)",
   "length": "45.5\"",
   "lie": "Standard",
   "setComp": null,
   "gripCond": "Good",
   "grip": "Golf Pride Tour Velvet",
   "headcover": true,
   "serial": null,
   "notes": "Real VeloCore Ventus Blue, not the made-for. Head is excellent.",
   "tradeEligible": true,
   "arrived": "2026-09-07",
   "find": false,
   "featured": true,
   "compare": null,
   "year": 2023
  },
  {
   "sku": "PWR-TM-STEALT-3WOOD-00111",
   "brand": "TaylorMade",
   "model": "Stealth 2 3 Wood",
   "cat": "wood",
   "club": "3 Wood",
   "price": 139,
   "cond": 8,
   "type": "used",
   "dex": "RH",
   "flex": "Stiff",
   "loft": "15\u00b0",
   "shaftBrand": "Fujikura",
   "shaftModel": "Ventus Red 6",
   "length": "43.25\"",
   "lie": "Standard",
   "setComp": null,
   "gripCond": "Good",
   "grip": "Golf Pride Tour Velvet",
   "headcover": true,
   "serial": null,
   "notes": "Clean face, minor sole scratches. Headcover included.",
   "tradeEligible": true,
   "arrived": "2026-09-04",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2023
  },
  {
   "sku": "PWR-TI-TSR23W-3WOOD-00112",
   "brand": "Titleist",
   "model": "TSR2 3 Wood",
   "cat": "wood",
   "club": "3 Wood",
   "price": 189,
   "cond": 9,
   "type": "used",
   "dex": "RH",
   "flex": "Stiff",
   "loft": "15\u00b0",
   "shaftBrand": "Mitsubishi",
   "shaftModel": "Tensei 1K Black 65",
   "length": "43\"",
   "lie": "Standard",
   "setComp": null,
   "gripCond": "Good",
   "grip": "Golf Pride Tour Velvet",
   "headcover": true,
   "serial": null,
   "notes": "Excellent. Barely a mark.",
   "tradeEligible": true,
   "arrived": "2026-09-06",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2023
  },
  {
   "sku": "PWR-CW-PARADY-5WOOD-00113",
   "brand": "Callaway",
   "model": "Paradym 5 Wood",
   "cat": "wood",
   "club": "5 Wood",
   "price": 149,
   "cond": 8,
   "type": "used",
   "dex": "RH",
   "flex": "Regular",
   "loft": "18\u00b0",
   "shaftBrand": "Aldila",
   "shaftModel": "Ascent 60",
   "length": "42.5\"",
   "lie": "Standard",
   "setComp": null,
   "gripCond": "Good",
   "grip": "Golf Pride Tour Velvet",
   "headcover": true,
   "serial": null,
   "notes": "Normal wear. Adjustable hosel wrench included.",
   "tradeEligible": true,
   "arrived": "2026-08-31",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2023
  },
  {
   "sku": "PWR-PG-G4303W-3WOOD-00114",
   "brand": "Ping",
   "model": "G430 3 Wood",
   "cat": "wood",
   "club": "3 Wood",
   "price": 169,
   "cond": 8,
   "type": "used",
   "dex": "RH",
   "flex": "Stiff",
   "loft": "15\u00b0",
   "shaftBrand": "Ping",
   "shaftModel": "Alta CB Black 65",
   "length": "43\"",
   "lie": "Standard",
   "setComp": null,
   "gripCond": "Good",
   "grip": "Golf Pride Tour Velvet",
   "headcover": true,
   "serial": null,
   "notes": "Solid. One faint scuff on the crown.",
   "tradeEligible": true,
   "arrived": "2026-09-02",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2023
  },
  {
   "sku": "PWR-TI-TSI33W-3WOOD-00115",
   "brand": "Titleist",
   "model": "TSi3 3 Wood",
   "cat": "wood",
   "club": "3 Wood",
   "price": 129,
   "cond": 7,
   "type": "used",
   "dex": "RH",
   "flex": "X-Stiff",
   "loft": "15\u00b0",
   "shaftBrand": "Graphite Design",
   "shaftModel": "Tour AD XC-7",
   "length": "43\"",
   "lie": "Standard",
   "setComp": null,
   "gripCond": "Good",
   "grip": "Golf Pride Tour Velvet",
   "headcover": true,
   "serial": null,
   "notes": "Weird one \u2014 Tour AD XC-7 X-flex in a 3 wood. Someone is going to love this.",
   "tradeEligible": true,
   "arrived": "2026-09-08",
   "find": true,
   "featured": true,
   "compare": null,
   "year": 2021
  },
  {
   "sku": "PWR-PG-G430HY-4HYBRI-00116",
   "brand": "Ping",
   "model": "G430 Hybrid",
   "cat": "hybrid",
   "club": "4 Hybrid",
   "price": 129,
   "cond": 8,
   "type": "used",
   "dex": "RH",
   "flex": "Stiff",
   "loft": "22\u00b0",
   "shaftBrand": "Ping",
   "shaftModel": "Alta CB Black 70",
   "length": "39.75\"",
   "lie": "Standard",
   "setComp": null,
   "gripCond": "Good",
   "grip": "Golf Pride Tour Velvet",
   "headcover": true,
   "serial": null,
   "notes": "Normal wear. Headcover included.",
   "tradeEligible": true,
   "arrived": "2026-08-29",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2023
  },
  {
   "sku": "PWR-TM-QI10RE-3HYBRI-00117",
   "brand": "TaylorMade",
   "model": "Qi10 Rescue",
   "cat": "hybrid",
   "club": "3 Hybrid",
   "price": 149,
   "cond": 9,
   "type": "used",
   "dex": "RH",
   "flex": "Stiff",
   "loft": "19\u00b0",
   "shaftBrand": "Fujikura",
   "shaftModel": "Ventus Blue HB 7",
   "length": "40.5\"",
   "lie": "Standard",
   "setComp": null,
   "gripCond": "Good",
   "grip": "Golf Pride Tour Velvet",
   "headcover": true,
   "serial": null,
   "notes": "Near new.",
   "tradeEligible": true,
   "arrived": "2026-09-07",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2024
  },
  {
   "sku": "PWR-TI-TSR2HY-5HYBRI-00118",
   "brand": "Titleist",
   "model": "TSR2 Hybrid",
   "cat": "hybrid",
   "club": "5 Hybrid",
   "price": 139,
   "cond": 8,
   "type": "used",
   "dex": "RH",
   "flex": "Regular",
   "loft": "24\u00b0",
   "shaftBrand": "Mitsubishi",
   "shaftModel": "Tensei AV Blue 75",
   "length": "39.5\"",
   "lie": "Standard",
   "setComp": null,
   "gripCond": "Good",
   "grip": "Golf Pride Tour Velvet",
   "headcover": true,
   "serial": null,
   "notes": "Clean. Regular flex.",
   "tradeEligible": true,
   "arrived": "2026-08-23",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2023
  },
  {
   "sku": "PWR-CW-APEXUW-UTILIT-00119",
   "brand": "Callaway",
   "model": "Apex UW",
   "cat": "hybrid",
   "club": "Utility Wood",
   "price": 119,
   "cond": 7,
   "type": "used",
   "dex": "RH",
   "flex": "Stiff",
   "loft": "19\u00b0",
   "shaftBrand": "Mitsubishi",
   "shaftModel": "MMT 80",
   "length": "41\"",
   "lie": "Standard",
   "setComp": null,
   "gripCond": "Good",
   "grip": "Golf Pride Tour Velvet",
   "headcover": false,
   "serial": null,
   "notes": "Between a 5 wood and a hybrid. Sole shows wear, face is fine.",
   "tradeEligible": true,
   "arrived": "2026-08-15",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2022
  },
  {
   "sku": "PWR-TM-P770-4PW-00120",
   "brand": "TaylorMade",
   "model": "P770",
   "cat": "iron",
   "club": "4-PW",
   "price": 649,
   "cond": 8,
   "type": "used",
   "dex": "RH",
   "flex": "Stiff",
   "loft": "Standard",
   "shaftBrand": "KBS",
   "shaftModel": "Tour 120",
   "length": "Standard",
   "lie": "Standard",
   "setComp": "4-PW (7 clubs)",
   "gripCond": "Good",
   "grip": "Golf Pride Tour Velvet",
   "headcover": true,
   "serial": null,
   "notes": "Small sky mark on the 4 iron, otherwise clean. Faces show normal groove wear. Grips are fine but not new.",
   "tradeEligible": true,
   "arrived": "2026-09-08",
   "find": false,
   "featured": true,
   "compare": null,
   "year": 2023
  },
  {
   "sku": "PWR-TM-P79020-5PWAW-00121",
   "brand": "TaylorMade",
   "model": "P790 (2023)",
   "cat": "iron",
   "club": "5-PW, AW",
   "price": 749,
   "cond": 9,
   "type": "used",
   "dex": "RH",
   "flex": "Stiff",
   "loft": "Standard",
   "shaftBrand": "True Temper",
   "shaftModel": "Dynamic Gold 105",
   "length": null,
   "lie": "Standard",
   "setComp": "5-PW, AW (7 clubs)",
   "gripCond": "Good",
   "grip": "Golf Pride Tour Velvet",
   "headcover": true,
   "serial": null,
   "notes": "Excellent. Just over a season of light play. Matching gap wedge included.",
   "tradeEligible": true,
   "arrived": "2026-09-05",
   "find": false,
   "featured": true,
   "compare": null,
   "year": 2023
  },
  {
   "sku": "PWR-TI-T150-4PW-00122",
   "brand": "Titleist",
   "model": "T150",
   "cat": "iron",
   "club": "4-PW",
   "price": 699,
   "cond": 9,
   "type": "used",
   "dex": "RH",
   "flex": "Stiff",
   "loft": "Standard",
   "shaftBrand": "Project X",
   "shaftModel": "Project X 6.0",
   "length": null,
   "lie": "1\u00b0 Upright",
   "setComp": "4-PW (7 clubs)",
   "gripCond": "Good",
   "grip": "Golf Pride Tour Velvet",
   "headcover": true,
   "serial": null,
   "notes": "Lie bent 1\u00b0 upright by previous owner \u2014 we checked every head on the machine. Fantastic shape.",
   "tradeEligible": true,
   "arrived": "2026-09-03",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2023
  },
  {
   "sku": "PWR-TI-T20020-5PW-00123",
   "brand": "Titleist",
   "model": "T200 (2021)",
   "cat": "iron",
   "club": "5-PW",
   "price": 449,
   "cond": 7,
   "type": "used",
   "dex": "RH",
   "flex": "Regular",
   "loft": "Standard",
   "shaftBrand": "True Temper",
   "shaftModel": "AMT Red",
   "length": null,
   "lie": "Standard",
   "setComp": "5-PW (6 clubs)",
   "gripCond": "Good",
   "grip": "Golf Pride Tour Velvet",
   "headcover": true,
   "serial": null,
   "notes": "Iron set under $500. Honest wear on the soles, faces are fine.",
   "tradeEligible": true,
   "arrived": "2026-08-10",
   "find": true,
   "featured": false,
   "compare": null,
   "year": 2021
  },
  {
   "sku": "PWR-MZ-JPX923-5GW-00124",
   "brand": "Mizuno",
   "model": "JPX 923 Forged",
   "cat": "iron",
   "club": "5-GW",
   "price": 599,
   "cond": 8,
   "type": "used",
   "dex": "RH",
   "flex": "Stiff",
   "loft": "Standard",
   "shaftBrand": "Nippon",
   "shaftModel": "Modus3 Tour 105",
   "length": null,
   "lie": "Standard",
   "setComp": "5-PW, GW (7 clubs)",
   "gripCond": "Good",
   "grip": "Golf Pride Tour Velvet",
   "headcover": true,
   "serial": null,
   "notes": "Mizuno forged feel. Normal play wear. Modus 105 is a great shaft.",
   "tradeEligible": true,
   "arrived": "2026-08-31",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2023
  },
  {
   "sku": "PWR-SX-ZX7MKI-4PW-00125",
   "brand": "Srixon",
   "model": "ZX7 Mk II",
   "cat": "iron",
   "club": "4-PW",
   "price": 599,
   "cond": 8,
   "type": "used",
   "dex": "RH",
   "flex": "Stiff",
   "loft": "Standard",
   "shaftBrand": "Nippon",
   "shaftModel": "Modus3 Tour 120",
   "length": null,
   "lie": "Standard",
   "setComp": "4-PW (7 clubs)",
   "gripCond": "Good",
   "grip": "Golf Pride Tour Velvet",
   "headcover": true,
   "serial": null,
   "notes": "Players' cavity. Faint sole wear only.",
   "tradeEligible": true,
   "arrived": "2026-08-28",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2023
  },
  {
   "sku": "PWR-PG-I230-4UW-00126",
   "brand": "Ping",
   "model": "i230",
   "cat": "iron",
   "club": "4-UW",
   "price": 749,
   "cond": 9,
   "type": "used",
   "dex": "RH",
   "flex": "Stiff",
   "loft": "Standard",
   "shaftBrand": "Ping",
   "shaftModel": "AWT 2.0",
   "length": null,
   "lie": "Black Dot",
   "setComp": "4-PW, UW (8 clubs)",
   "gripCond": "Good",
   "grip": "Golf Pride Tour Velvet",
   "headcover": true,
   "serial": null,
   "notes": "Black dot (standard lie). Eight clubs including the UW. Barely played.",
   "tradeEligible": true,
   "arrived": "2026-09-06",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2023
  },
  {
   "sku": "PWR-CW-APEXPR-4PW-00127",
   "brand": "Callaway",
   "model": "Apex Pro 21",
   "cat": "iron",
   "club": "4-PW",
   "price": 399,
   "cond": 7,
   "type": "used",
   "dex": "RH",
   "flex": "Stiff",
   "loft": "Standard",
   "shaftBrand": "True Temper",
   "shaftModel": "Elevate Tour 115",
   "length": null,
   "lie": "Standard",
   "setComp": "4-PW (7 clubs)",
   "gripCond": "Good",
   "grip": "Golf Pride Tour Velvet",
   "headcover": true,
   "serial": null,
   "notes": "Iron set under $500. Some face wear on the short irons. Great feel.",
   "tradeEligible": true,
   "arrived": "2026-08-18",
   "find": true,
   "featured": false,
   "compare": null,
   "year": 2021
  },
  {
   "sku": "PWR-CW-PARADY-5AW-00128",
   "brand": "Callaway",
   "model": "Paradym Ai Smoke",
   "cat": "iron",
   "club": "5-AW",
   "price": 549,
   "cond": 9,
   "type": "used",
   "dex": "RH",
   "flex": "Regular",
   "loft": "Standard",
   "shaftBrand": "True Temper",
   "shaftModel": "Dynamic Gold Mid 100",
   "length": null,
   "lie": "Standard",
   "setComp": "5-PW, AW (7 clubs)",
   "gripCond": "Good",
   "grip": "Golf Pride Tour Velvet",
   "headcover": true,
   "serial": null,
   "notes": "Regular flex, game-improvement. Very light wear.",
   "tradeEligible": true,
   "arrived": "2026-09-04",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2024
  },
  {
   "sku": "PWR-MZ-PRO245-4PW-00129",
   "brand": "Mizuno",
   "model": "Pro 245",
   "cat": "iron",
   "club": "4-PW",
   "price": 699,
   "cond": 8,
   "type": "used",
   "dex": "LH",
   "flex": "Stiff",
   "loft": "Standard",
   "shaftBrand": "Project X",
   "shaftModel": "LZ 6.0",
   "length": null,
   "lie": "Standard",
   "setComp": "4-PW (7 clubs)",
   "gripCond": "Good",
   "grip": "Golf Pride Tour Velvet",
   "headcover": true,
   "serial": null,
   "notes": "Left-handed forged Mizunos. These don't come up often.",
   "tradeEligible": true,
   "arrived": "2026-09-01",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2024
  },
  {
   "sku": "PWR-CB-KINGFO-4GW-00130",
   "brand": "Cobra",
   "model": "King Forged Tec",
   "cat": "iron",
   "club": "4-GW",
   "price": 379,
   "cond": 7,
   "type": "used",
   "dex": "RH",
   "flex": "Stiff",
   "loft": "Standard",
   "shaftBrand": "KBS",
   "shaftModel": "$-Taper 120",
   "length": null,
   "lie": "Standard",
   "setComp": "4-PW, GW (8 clubs)",
   "gripCond": "Worn",
   "grip": "Golf Pride Tour Velvet",
   "headcover": true,
   "serial": null,
   "notes": "Iron set under $500. Eight clubs. Grips need replacing \u2014 we'll do it at cost with purchase.",
   "tradeEligible": true,
   "arrived": "2026-08-22",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2022
  },
  {
   "sku": "PWR-TI-T10020-4PW-00131",
   "brand": "Titleist",
   "model": "T100 (2021)",
   "cat": "iron",
   "club": "4-PW",
   "price": 549,
   "cond": 7,
   "type": "used",
   "dex": "RH",
   "flex": "X-Stiff",
   "loft": "Standard",
   "shaftBrand": "Project X",
   "shaftModel": "Project X 6.5",
   "length": null,
   "lie": "Standard",
   "setComp": "4-PW (7 clubs)",
   "gripCond": "Good",
   "grip": "Golf Pride Tour Velvet",
   "headcover": true,
   "serial": null,
   "notes": "X-flex Project X 6.5. Honest wear, plays great.",
   "tradeEligible": true,
   "arrived": "2026-08-26",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2021
  },
  {
   "sku": "PWR-VK-SM10-54SGRI-00132",
   "brand": "Vokey",
   "model": "SM10",
   "cat": "wedge",
   "club": "54\u00b0 S Grind",
   "price": 139,
   "cond": 9.5,
   "type": "used",
   "dex": "RH",
   "flex": "Wedge",
   "loft": "54\u00b0",
   "shaftBrand": "True Temper",
   "shaftModel": "Dynamic Gold S200",
   "length": null,
   "lie": "Standard",
   "setComp": null,
   "gripCond": "Good",
   "grip": "Golf Pride Tour Velvet 360",
   "headcover": true,
   "serial": null,
   "notes": "Mint. Grooves are sharp enough to shave with. Original grip.",
   "tradeEligible": true,
   "arrived": "2026-09-09",
   "find": true,
   "featured": true,
   "compare": null,
   "year": 2024,
   "bounce": "10\u00b0"
  },
  {
   "sku": "PWR-VK-SM10-58MGRI-00133",
   "brand": "Vokey",
   "model": "SM10",
   "cat": "wedge",
   "club": "58\u00b0 M Grind",
   "price": 139,
   "cond": 9.5,
   "type": "used",
   "dex": "RH",
   "flex": "Wedge",
   "loft": "58\u00b0",
   "shaftBrand": "True Temper",
   "shaftModel": "Dynamic Gold S200",
   "length": null,
   "lie": "Standard",
   "setComp": null,
   "gripCond": "Good",
   "grip": "Golf Pride Tour Velvet",
   "headcover": true,
   "serial": null,
   "notes": "Mint, matches the 54. Buy both and we'll knock $20 off at the counter.",
   "tradeEligible": true,
   "arrived": "2026-09-09",
   "find": true,
   "featured": false,
   "compare": null,
   "year": 2024,
   "bounce": "8\u00b0"
  },
  {
   "sku": "PWR-VK-SM9-50FGRI-00134",
   "brand": "Vokey",
   "model": "SM9",
   "cat": "wedge",
   "club": "50\u00b0 F Grind",
   "price": 89,
   "cond": 8,
   "type": "used",
   "dex": "RH",
   "flex": "Wedge",
   "loft": "50\u00b0",
   "shaftBrand": "True Temper",
   "shaftModel": "Dynamic Gold S200",
   "length": null,
   "lie": "Standard",
   "setComp": null,
   "gripCond": "Good",
   "grip": "Golf Pride Tour Velvet",
   "headcover": true,
   "serial": null,
   "notes": "Very good. Light face wear.",
   "tradeEligible": true,
   "arrived": "2026-08-27",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2022,
   "bounce": "12\u00b0"
  },
  {
   "sku": "PWR-CL-RTX6ZI-56MID-00135",
   "brand": "Cleveland",
   "model": "RTX 6 ZipCore",
   "cat": "wedge",
   "club": "56\u00b0 Mid",
   "price": 79,
   "cond": 8,
   "type": "used",
   "dex": "RH",
   "flex": "Wedge",
   "loft": "56\u00b0",
   "shaftBrand": "True Temper",
   "shaftModel": "Dynamic Gold Spinner",
   "length": null,
   "lie": "Standard",
   "setComp": null,
   "gripCond": "Good",
   "grip": "Golf Pride Tour Velvet",
   "headcover": true,
   "serial": null,
   "notes": "Clean. Tour satin finish.",
   "tradeEligible": true,
   "arrived": "2026-09-02",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2023,
   "bounce": "10\u00b0"
  },
  {
   "sku": "PWR-TM-MG4-60SB-00136",
   "brand": "TaylorMade",
   "model": "MG4",
   "cat": "wedge",
   "club": "60\u00b0 SB",
   "price": 89,
   "cond": 8,
   "type": "used",
   "dex": "RH",
   "flex": "Wedge",
   "loft": "60\u00b0",
   "shaftBrand": "True Temper",
   "shaftModel": "Dynamic Gold Tour Issue S200",
   "length": null,
   "lie": "Standard",
   "setComp": null,
   "gripCond": "Good",
   "grip": "Golf Pride Tour Velvet",
   "headcover": true,
   "serial": null,
   "notes": "Raw face has rusted as designed. Good grooves.",
   "tradeEligible": true,
   "arrived": "2026-08-30",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2023,
   "bounce": "8\u00b0"
  },
  {
   "sku": "PWR-CW-JAWSRA-52S-00137",
   "brand": "Callaway",
   "model": "Jaws Raw",
   "cat": "wedge",
   "club": "52\u00b0 S",
   "price": 69,
   "cond": 7,
   "type": "used",
   "dex": "RH",
   "flex": "Wedge",
   "loft": "52\u00b0",
   "shaftBrand": "True Temper",
   "shaftModel": "Dynamic Gold Spinner",
   "length": null,
   "lie": "Standard",
   "setComp": null,
   "gripCond": "Worn",
   "grip": "Golf Pride Tour Velvet",
   "headcover": true,
   "serial": null,
   "notes": "Honest wear. Grip is worn \u2014 replaced free with purchase.",
   "tradeEligible": true,
   "arrived": "2026-08-12",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2022,
   "bounce": "10\u00b0"
  },
  {
   "sku": "PWR-PG-GLIDE4-56SS-00138",
   "brand": "Ping",
   "model": "Glide 4.0",
   "cat": "wedge",
   "club": "56\u00b0 SS",
   "price": 79,
   "cond": 8,
   "type": "used",
   "dex": "RH",
   "flex": "Wedge",
   "loft": "56\u00b0",
   "shaftBrand": "Ping",
   "shaftModel": "Z-Z115",
   "length": null,
   "lie": "Standard",
   "setComp": null,
   "gripCond": "Good",
   "grip": "Golf Pride Tour Velvet",
   "headcover": true,
   "serial": null,
   "notes": "Good grooves. Standard lie.",
   "tradeEligible": true,
   "arrived": "2026-08-24",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2022,
   "bounce": "12\u00b0"
  },
  {
   "sku": "PWR-TI-VOKEYW-60TGRI-00139",
   "brand": "Titleist",
   "model": "Vokey WedgeWorks",
   "cat": "wedge",
   "club": "60\u00b0 T Grind (Raw)",
   "price": 119,
   "cond": 8,
   "type": "used",
   "dex": "RH",
   "flex": "Wedge",
   "loft": "60\u00b0",
   "shaftBrand": "True Temper",
   "shaftModel": "Dynamic Gold S400",
   "length": null,
   "lie": "Standard",
   "setComp": null,
   "gripCond": "Good",
   "grip": "Golf Pride Tour Velvet",
   "headcover": true,
   "serial": null,
   "notes": "Low bounce T grind, raw finish. Great for firm Florida lies.",
   "tradeEligible": true,
   "arrived": "2026-09-03",
   "find": true,
   "featured": false,
   "compare": null,
   "year": 2023,
   "bounce": "4\u00b0"
  },
  {
   "sku": "PWR-SC-NEWPOR-PUTTER-00140",
   "brand": "Scotty Cameron",
   "model": "Newport 2 (2018)",
   "cat": "putter",
   "club": "Putter",
   "price": 319,
   "cond": 8,
   "type": "used",
   "dex": "RH",
   "flex": "\u2014",
   "loft": null,
   "shaftBrand": "Scotty Cameron",
   "shaftModel": "Steel",
   "length": "34\"",
   "lie": "Standard",
   "setComp": null,
   "gripCond": "Good",
   "grip": "Pistolini Plus",
   "headcover": true,
   "serial": "\u20264Q12",
   "notes": "Older Scotty. A few faint marks on the sole, face is clean. Original headcover, original Pistolini grip. This is the one people ask about.",
   "tradeEligible": true,
   "arrived": "2026-09-07",
   "find": true,
   "featured": true,
   "compare": null,
   "year": 2018
  },
  {
   "sku": "PWR-SC-PHANTO-PUTTER-00141",
   "brand": "Scotty Cameron",
   "model": "Phantom 5.5",
   "cat": "putter",
   "club": "Putter",
   "price": 349,
   "cond": 9,
   "type": "used",
   "dex": "RH",
   "flex": "\u2014",
   "loft": null,
   "shaftBrand": "Scotty Cameron",
   "shaftModel": "Steel",
   "length": "35\"",
   "lie": "Standard",
   "setComp": null,
   "gripCond": "Good",
   "grip": "Pistolero Plus",
   "headcover": true,
   "serial": null,
   "notes": "Excellent. Headcover included.",
   "tradeEligible": true,
   "arrived": "2026-09-04",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2022
  },
  {
   "sku": "PWR-OD-WHITEH-PUTTER-00142",
   "brand": "Odyssey",
   "model": "White Hot OG #7",
   "cat": "putter",
   "club": "Putter",
   "price": 139,
   "cond": 8,
   "type": "used",
   "dex": "RH",
   "flex": "\u2014",
   "loft": null,
   "shaftBrand": "Odyssey",
   "shaftModel": "Stroke Lab",
   "length": "34\"",
   "lie": "Standard",
   "setComp": null,
   "gripCond": "Good",
   "grip": "Odyssey Oversize",
   "headcover": true,
   "serial": null,
   "notes": "Stroke Lab shaft. Insert is clean.",
   "tradeEligible": true,
   "arrived": "2026-08-31",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2021
  },
  {
   "sku": "PWR-OD-AIONEJ-PUTTER-00143",
   "brand": "Odyssey",
   "model": "Ai-One Jailbird Mini",
   "cat": "putter",
   "club": "Putter",
   "price": 189,
   "cond": 9,
   "type": "used",
   "dex": "RH",
   "flex": "\u2014",
   "loft": null,
   "shaftBrand": "Odyssey",
   "shaftModel": "Stroke Lab",
   "length": "34\"",
   "lie": "Standard",
   "setComp": null,
   "gripCond": "Good",
   "grip": "SuperStroke Traxion Tour 2.0",
   "headcover": true,
   "serial": null,
   "notes": "Excellent. Headcover included. SuperStroke grip in great shape.",
   "tradeEligible": true,
   "arrived": "2026-09-06",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2024
  },
  {
   "sku": "PWR-PG-PLDANS-PUTTER-00144",
   "brand": "Ping",
   "model": "PLD Anser 2",
   "cat": "putter",
   "club": "Putter",
   "price": 279,
   "cond": 9,
   "type": "used",
   "dex": "RH",
   "flex": "\u2014",
   "loft": null,
   "shaftBrand": "Ping",
   "shaftModel": "Steel",
   "length": "34\"",
   "lie": "Standard",
   "setComp": null,
   "gripCond": "Good",
   "grip": "Ping PP58",
   "headcover": true,
   "serial": null,
   "notes": "Milled Ping. Near new.",
   "tradeEligible": true,
   "arrived": "2026-09-05",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2023
  },
  {
   "sku": "PWR-TM-SPIDER-PUTTER-00145",
   "brand": "TaylorMade",
   "model": "Spider Tour X",
   "cat": "putter",
   "club": "Putter",
   "price": 229,
   "cond": 9,
   "type": "used",
   "dex": "RH",
   "flex": "\u2014",
   "loft": null,
   "shaftBrand": "TaylorMade",
   "shaftModel": "Steel (double bend)",
   "length": "35\"",
   "lie": "Standard",
   "setComp": null,
   "gripCond": "Good",
   "grip": "SuperStroke Pistol GT 1.0",
   "headcover": true,
   "serial": null,
   "notes": "Excellent. Headcover included.",
   "tradeEligible": true,
   "arrived": "2026-09-03",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2023
  },
  {
   "sku": "PWR-SC-SPECIA-PUTTER-00146",
   "brand": "Scotty Cameron",
   "model": "Special Select Squareback 2",
   "cat": "putter",
   "club": "Putter",
   "price": 299,
   "cond": 8,
   "type": "used",
   "dex": "RH",
   "flex": "\u2014",
   "loft": null,
   "shaftBrand": "Scotty Cameron",
   "shaftModel": "Steel",
   "length": "33\"",
   "lie": "Standard",
   "setComp": null,
   "gripCond": "Good",
   "grip": "Pistolero Plus",
   "headcover": true,
   "serial": null,
   "notes": "33\" \u2014 shorter than most. Sole shows some marks; described honestly in the photos.",
   "tradeEligible": true,
   "arrived": "2026-08-29",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2020
  },
  {
   "sku": "PWR-OD-2BALLT-PUTTER-00147",
   "brand": "Odyssey",
   "model": "2-Ball Ten",
   "cat": "putter",
   "club": "Putter",
   "price": 119,
   "cond": 7,
   "type": "used",
   "dex": "LH",
   "flex": "\u2014",
   "loft": null,
   "shaftBrand": "Odyssey",
   "shaftModel": "Stroke Lab",
   "length": "35\"",
   "lie": "Standard",
   "setComp": null,
   "gripCond": "Good",
   "grip": "Golf Pride Tour Velvet",
   "headcover": false,
   "serial": null,
   "notes": "Left-handed. Honest wear on the sole, alignment lines a bit faded.",
   "tradeEligible": true,
   "arrived": "2026-08-21",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2021
  },
  {
   "sku": "PWR-GD-TOURAD-DRIVER-00148",
   "brand": "Graphite Design",
   "model": "Tour AD IZ-6",
   "cat": "shaft",
   "club": "Driver Shaft",
   "price": 199,
   "cond": 8,
   "type": "used",
   "dex": "RH",
   "flex": "Stiff",
   "loft": null,
   "shaftBrand": "Graphite Design",
   "shaftModel": "Tour AD IZ-6",
   "length": "44\"",
   "lie": "Standard",
   "setComp": null,
   "gripCond": "Good",
   "grip": "Golf Pride Tour Velvet",
   "headcover": false,
   "serial": null,
   "notes": "Weird Tour AD shaft alert. Pulled from a Titleist TSi3, adapter included. Tipped 0.5\". These sell for $400+ new.",
   "tradeEligible": true,
   "arrived": "2026-09-09",
   "find": true,
   "featured": true,
   "compare": null,
   "year": null
  },
  {
   "sku": "PWR-FJ-VENTUS-DRIVER-00149",
   "brand": "Fujikura",
   "model": "Ventus Black 6 (VeloCore)",
   "cat": "shaft",
   "club": "Driver Shaft",
   "price": 179,
   "cond": 8,
   "type": "used",
   "dex": "RH",
   "flex": "X-Stiff",
   "loft": null,
   "shaftBrand": "Fujikura",
   "shaftModel": "Ventus Black 6",
   "length": "44.25\"",
   "lie": "Standard",
   "setComp": null,
   "gripCond": "Good",
   "grip": "Golf Pride Tour Velvet",
   "headcover": false,
   "serial": null,
   "notes": "Real VeloCore. TaylorMade adapter installed. Untipped.",
   "tradeEligible": true,
   "arrived": "2026-09-06",
   "find": false,
   "featured": false,
   "compare": null,
   "year": null
  },
  {
   "sku": "PWR-PX-HZRDUS-DRIVER-00150",
   "brand": "Project X",
   "model": "HZRDUS Smoke Black RDX 60",
   "cat": "shaft",
   "club": "Driver Shaft",
   "price": 89,
   "cond": 8,
   "type": "used",
   "dex": "RH",
   "flex": "Stiff",
   "loft": null,
   "shaftBrand": "Project X",
   "shaftModel": "HZRDUS Smoke Black RDX 60",
   "length": "44.5\"",
   "lie": "Standard",
   "setComp": null,
   "gripCond": "Good",
   "grip": "Golf Pride Tour Velvet",
   "headcover": false,
   "serial": null,
   "notes": "Callaway adapter. Clean.",
   "tradeEligible": true,
   "arrived": "2026-08-31",
   "find": false,
   "featured": false,
   "compare": null,
   "year": null
  },
  {
   "sku": "PWR-MC-DIAMAN-DRIVER-00151",
   "brand": "Mitsubishi",
   "model": "Diamana PD 60",
   "cat": "shaft",
   "club": "Driver Shaft",
   "price": 119,
   "cond": 8,
   "type": "used",
   "dex": "RH",
   "flex": "Stiff",
   "loft": null,
   "shaftBrand": "Mitsubishi",
   "shaftModel": "Diamana PD 60",
   "length": "44.25\"",
   "lie": "Standard",
   "setComp": null,
   "gripCond": "Good",
   "grip": "Golf Pride Tour Velvet",
   "headcover": false,
   "serial": null,
   "notes": "Ping adapter. Tipped 1\".",
   "tradeEligible": true,
   "arrived": "2026-08-26",
   "find": false,
   "featured": false,
   "compare": null,
   "year": null
  },
  {
   "sku": "PWR-KB-TOUR12-IRONSH-00152",
   "brand": "KBS",
   "model": "Tour 120 (5-PW pulls)",
   "cat": "shaft",
   "club": "Iron Shafts",
   "price": 149,
   "cond": 8,
   "type": "used",
   "dex": "RH",
   "flex": "Stiff",
   "loft": null,
   "shaftBrand": "KBS",
   "shaftModel": "Tour 120",
   "length": "Standard",
   "lie": "Standard",
   "setComp": null,
   "gripCond": "Good",
   "grip": "Golf Pride Tour Velvet",
   "headcover": false,
   "serial": null,
   "notes": "Set of six .355 taper tip pulls, uncut butt. Ready to build.",
   "tradeEligible": true,
   "arrived": "2026-09-03",
   "find": false,
   "featured": false,
   "compare": null,
   "year": null
  },
  {
   "sku": "PWR-CW-STRATA-COMPLE-00153",
   "brand": "Callaway",
   "model": "Strata Complete Set",
   "cat": "set",
   "club": "Complete Set",
   "price": 229,
   "cond": 7,
   "type": "used",
   "dex": "RH",
   "flex": "Regular",
   "loft": null,
   "shaftBrand": null,
   "shaftModel": null,
   "length": null,
   "lie": "Standard",
   "setComp": "Driver, 3W, 5H, 6-PW, SW, Putter, Bag (12 pcs)",
   "gripCond": "Good",
   "grip": "Golf Pride Tour Velvet",
   "headcover": true,
   "serial": null,
   "notes": "Solid starter set with a stand bag. Honest wear. Cleaned and regripped where needed.",
   "tradeEligible": true,
   "arrived": "2026-08-28",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2022
  },
  {
   "sku": "PWR-CB-FLYXLC-COMPLE-00154",
   "brand": "Cobra",
   "model": "Fly-XL Complete Set",
   "cat": "set",
   "club": "Complete Set",
   "price": 349,
   "cond": 8,
   "type": "used",
   "dex": "RH",
   "flex": "Regular",
   "loft": null,
   "shaftBrand": null,
   "shaftModel": null,
   "length": null,
   "lie": "Standard",
   "setComp": "Driver, 3W, 4H, 5-PW, SW, Putter, Bag (13 pcs)",
   "gripCond": "Good",
   "grip": "Golf Pride Tour Velvet",
   "headcover": true,
   "serial": null,
   "notes": "Very good shape. Great first real set.",
   "tradeEligible": true,
   "arrived": "2026-09-01",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2023
  },
  {
   "sku": "PWR-PG-G430FU-FULLBA-00155",
   "brand": "Ping",
   "model": "G430 Full Bag",
   "cat": "set",
   "club": "Full Bag",
   "price": 1899,
   "cond": 8,
   "type": "used",
   "dex": "RH",
   "flex": "Stiff",
   "loft": null,
   "shaftBrand": null,
   "shaftModel": null,
   "length": null,
   "lie": "Standard",
   "setComp": "G430 Max Driver, 3W, 4H, 5-UW, Glide 4.0 56/60, PLD Anser, Hoofer bag",
   "gripCond": "Good",
   "grip": "Golf Pride Tour Velvet",
   "headcover": true,
   "serial": null,
   "notes": "We bought this whole bag from a member moving north. Everything in it is 2023\u201324 Ping. Ask us to split it.",
   "tradeEligible": true,
   "arrived": "2026-09-08",
   "find": true,
   "featured": true,
   "compare": null,
   "year": 2023
  },
  {
   "sku": "PWR-VS-PLAYER-STANDB-00156",
   "brand": "Vessel",
   "model": "Player IV Pro Stand Bag",
   "cat": "bag",
   "club": "Stand Bag",
   "price": 229,
   "cond": 8,
   "type": "used",
   "dex": "RH",
   "flex": "\u2014",
   "loft": null,
   "shaftBrand": null,
   "shaftModel": null,
   "length": null,
   "lie": "Standard",
   "setComp": null,
   "gripCond": "Good",
   "grip": "Golf Pride Tour Velvet",
   "headcover": false,
   "serial": null,
   "notes": "Vessel quality. Light wear on the base. Rain hood included.",
   "tradeEligible": true,
   "arrived": "2026-09-04",
   "find": false,
   "featured": false,
   "compare": null,
   "year": null
  },
  {
   "sku": "PWR-TI-PLAYER-STANDB-00157",
   "brand": "Titleist",
   "model": "Players 4 Plus StaDry",
   "cat": "bag",
   "club": "Stand Bag",
   "price": 149,
   "cond": 8,
   "type": "used",
   "dex": "RH",
   "flex": "\u2014",
   "loft": null,
   "shaftBrand": null,
   "shaftModel": null,
   "length": null,
   "lie": "Standard",
   "setComp": null,
   "gripCond": "Good",
   "grip": "Golf Pride Tour Velvet",
   "headcover": false,
   "serial": null,
   "notes": "Waterproof. Clean.",
   "tradeEligible": true,
   "arrived": "2026-08-30",
   "find": false,
   "featured": false,
   "compare": null,
   "year": null
  }
 ],
 "new": [
  {
   "sku": "PWR-TM-QI35DR-DRIVER-00158",
   "brand": "TaylorMade",
   "model": "Qi35 Driver",
   "cat": "driver",
   "club": "Driver",
   "price": 599,
   "cond": 10,
   "type": "new",
   "dex": "RH/LH",
   "flex": "R/S/X",
   "loft": "9\u00b0 / 10.5\u00b0",
   "shaftBrand": "Fujikura",
   "shaftModel": "Ventus Blue 6 (stock)",
   "length": "Standard",
   "lie": "Standard",
   "setComp": null,
   "notes": "Custom shaft options available in-store.",
   "headcover": true,
   "gripCond": "New",
   "grip": "Stock",
   "tradeEligible": false,
   "arrived": "2026-08-01",
   "find": false,
   "featured": true,
   "compare": null,
   "year": 2025,
   "stock": 2
  },
  {
   "sku": "PWR-TI-GT3DRI-DRIVER-00159",
   "brand": "Titleist",
   "model": "GT3 Driver",
   "cat": "driver",
   "club": "Driver",
   "price": 649,
   "cond": 10,
   "type": "new",
   "dex": "RH/LH",
   "flex": "R/S/X",
   "loft": "9\u00b0 / 10\u00b0",
   "shaftBrand": "Mitsubishi",
   "shaftModel": "Tensei 1K Black",
   "length": "Standard",
   "lie": "Standard",
   "setComp": null,
   "notes": "",
   "headcover": true,
   "gripCond": "New",
   "grip": "Stock",
   "tradeEligible": false,
   "arrived": "2026-08-09",
   "find": false,
   "featured": true,
   "compare": null,
   "year": 2025,
   "stock": 6
  },
  {
   "sku": "PWR-CW-ELYTET-DRIVER-00160",
   "brand": "Callaway",
   "model": "Elyte Triple Diamond",
   "cat": "driver",
   "club": "Driver",
   "price": 599,
   "cond": 10,
   "type": "new",
   "dex": "RH/LH",
   "flex": "R/S/X",
   "loft": "9\u00b0",
   "shaftBrand": "Project X",
   "shaftModel": "Denali Black",
   "length": "Standard",
   "lie": "Standard",
   "setComp": null,
   "notes": "",
   "headcover": true,
   "gripCond": "New",
   "grip": "Stock",
   "tradeEligible": false,
   "arrived": "2026-08-06",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2025,
   "stock": 4
  },
  {
   "sku": "PWR-PG-G440MA-DRIVER-00161",
   "brand": "Ping",
   "model": "G440 Max",
   "cat": "driver",
   "club": "Driver",
   "price": 579,
   "cond": 10,
   "type": "new",
   "dex": "RH/LH",
   "flex": "R/S/X",
   "loft": "9\u00b0 / 10.5\u00b0 / 12\u00b0",
   "shaftBrand": "Ping",
   "shaftModel": "Alta CB Black",
   "length": "Standard",
   "lie": "Standard",
   "setComp": null,
   "notes": "",
   "headcover": true,
   "gripCond": "New",
   "grip": "Stock",
   "tradeEligible": false,
   "arrived": "2026-07-22",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2025,
   "stock": 3
  },
  {
   "sku": "PWR-CB-DSADAP-DRIVER-00162",
   "brand": "Cobra",
   "model": "DS-ADAPT X",
   "cat": "driver",
   "club": "Driver",
   "price": 549,
   "cond": 10,
   "type": "new",
   "dex": "RH/LH",
   "flex": "R/S/X",
   "loft": "9\u00b0 / 10.5\u00b0",
   "shaftBrand": "UST",
   "shaftModel": "LIN-Q M40X",
   "length": "Standard",
   "lie": "Standard",
   "setComp": null,
   "notes": "",
   "headcover": true,
   "gripCond": "New",
   "grip": "Stock",
   "tradeEligible": false,
   "arrived": "2026-08-11",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2025,
   "stock": 5
  },
  {
   "sku": "PWR-TI-GT2FAI-WOOD-00163",
   "brand": "Titleist",
   "model": "GT2 Fairway",
   "cat": "wood",
   "club": "Wood",
   "price": 399,
   "cond": 10,
   "type": "new",
   "dex": "RH/LH",
   "flex": "R/S/X",
   "loft": "15\u00b0 / 18\u00b0",
   "shaftBrand": "Mitsubishi",
   "shaftModel": "Tensei 1K Blue",
   "length": "Standard",
   "lie": "Standard",
   "setComp": null,
   "notes": "",
   "headcover": true,
   "gripCond": "New",
   "grip": "Stock",
   "tradeEligible": false,
   "arrived": "2026-07-12",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2025,
   "stock": 4
  },
  {
   "sku": "PWR-TM-QI35FA-WOOD-00164",
   "brand": "TaylorMade",
   "model": "Qi35 Fairway",
   "cat": "wood",
   "club": "Wood",
   "price": 349,
   "cond": 10,
   "type": "new",
   "dex": "RH/LH",
   "flex": "R/S/X",
   "loft": "15\u00b0 / 18\u00b0",
   "shaftBrand": "Fujikura",
   "shaftModel": "Speeder NX",
   "length": "Standard",
   "lie": "Standard",
   "setComp": null,
   "notes": "",
   "headcover": true,
   "gripCond": "New",
   "grip": "Stock",
   "tradeEligible": false,
   "arrived": "2026-08-17",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2025,
   "stock": 3
  },
  {
   "sku": "PWR-PG-G440HY-HYBRID-00165",
   "brand": "Ping",
   "model": "G440 Hybrid",
   "cat": "hybrid",
   "club": "Hybrid",
   "price": 299,
   "cond": 10,
   "type": "new",
   "dex": "RH/LH",
   "flex": "R/S/X",
   "loft": "19\u00b0 / 22\u00b0",
   "shaftBrand": "Ping",
   "shaftModel": "Alta CB Black",
   "length": "Standard",
   "lie": "Standard",
   "setComp": null,
   "notes": "",
   "headcover": true,
   "gripCond": "New",
   "grip": "Stock",
   "tradeEligible": false,
   "arrived": "2026-08-25",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2025,
   "stock": 2
  },
  {
   "sku": "PWR-TI-GT2HYB-HYBRID-00166",
   "brand": "Titleist",
   "model": "GT2 Hybrid",
   "cat": "hybrid",
   "club": "Hybrid",
   "price": 329,
   "cond": 10,
   "type": "new",
   "dex": "RH/LH",
   "flex": "R/S/X",
   "loft": "18\u00b0 / 21\u00b0 / 24\u00b0",
   "shaftBrand": "Mitsubishi",
   "shaftModel": "Tensei 1K Blue",
   "length": "Standard",
   "lie": "Standard",
   "setComp": null,
   "notes": "",
   "headcover": true,
   "gripCond": "New",
   "grip": "Stock",
   "tradeEligible": false,
   "arrived": "2026-07-27",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2025,
   "stock": 2
  },
  {
   "sku": "PWR-TM-P79020-IRON-00167",
   "brand": "TaylorMade",
   "model": "P790 (2025)",
   "cat": "iron",
   "club": "Iron",
   "price": 1399,
   "cond": 10,
   "type": "new",
   "dex": "RH/LH",
   "flex": "R/S/X",
   "loft": null,
   "shaftBrand": "True Temper",
   "shaftModel": "Dynamic Gold 105 / KBS Tour",
   "length": "Standard",
   "lie": "Standard",
   "setComp": "4-PW (7 clubs)",
   "notes": "Built to your specs in our shop, usually same week.",
   "headcover": true,
   "gripCond": "New",
   "grip": "Stock",
   "tradeEligible": false,
   "arrived": "2026-09-04",
   "find": false,
   "featured": true,
   "compare": null,
   "year": 2025,
   "stock": 5
  },
  {
   "sku": "PWR-TI-T150-IRON-00168",
   "brand": "Titleist",
   "model": "T150",
   "cat": "iron",
   "club": "Iron",
   "price": 1499,
   "cond": 10,
   "type": "new",
   "dex": "RH/LH",
   "flex": "R/S/X",
   "loft": null,
   "shaftBrand": "Project X",
   "shaftModel": "Project X / AMT White",
   "length": "Standard",
   "lie": "Standard",
   "setComp": "4-PW (7 clubs)",
   "notes": "",
   "headcover": true,
   "gripCond": "New",
   "grip": "Stock",
   "tradeEligible": false,
   "arrived": "2026-08-21",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2025,
   "stock": 5
  },
  {
   "sku": "PWR-MZ-JPX925-IRON-00169",
   "brand": "Mizuno",
   "model": "JPX 925 Forged",
   "cat": "iron",
   "club": "Iron",
   "price": 1299,
   "cond": 10,
   "type": "new",
   "dex": "RH/LH",
   "flex": "R/S/X",
   "loft": null,
   "shaftBrand": "Nippon",
   "shaftModel": "Modus3 / KBS",
   "length": "Standard",
   "lie": "Standard",
   "setComp": "4-GW (8 clubs)",
   "notes": "",
   "headcover": true,
   "gripCond": "New",
   "grip": "Stock",
   "tradeEligible": false,
   "arrived": "2026-08-09",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2025,
   "stock": 3
  },
  {
   "sku": "PWR-SX-ZXI7-IRON-00170",
   "brand": "Srixon",
   "model": "ZXi7",
   "cat": "iron",
   "club": "Iron",
   "price": 1299,
   "cond": 10,
   "type": "new",
   "dex": "RH/LH",
   "flex": "R/S/X",
   "loft": null,
   "shaftBrand": "Nippon",
   "shaftModel": "Modus3 Tour 120",
   "length": "Standard",
   "lie": "Standard",
   "setComp": "4-PW (7 clubs)",
   "notes": "",
   "headcover": true,
   "gripCond": "New",
   "grip": "Stock",
   "tradeEligible": false,
   "arrived": "2026-07-25",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2025,
   "stock": 4
  },
  {
   "sku": "PWR-PG-I240-IRON-00171",
   "brand": "Ping",
   "model": "i240",
   "cat": "iron",
   "club": "Iron",
   "price": 1449,
   "cond": 10,
   "type": "new",
   "dex": "RH/LH",
   "flex": "R/S/X",
   "loft": null,
   "shaftBrand": "Ping",
   "shaftModel": "AWT 3.0 / Modus",
   "length": "Standard",
   "lie": "Standard",
   "setComp": "4-UW (8 clubs)",
   "notes": "",
   "headcover": true,
   "gripCond": "New",
   "grip": "Stock",
   "tradeEligible": false,
   "arrived": "2026-08-22",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2025,
   "stock": 5
  },
  {
   "sku": "PWR-CW-APEXAI-IRON-00172",
   "brand": "Callaway",
   "model": "Apex Ai200",
   "cat": "iron",
   "club": "Iron",
   "price": 1399,
   "cond": 10,
   "type": "new",
   "dex": "RH/LH",
   "flex": "R/S/X",
   "loft": null,
   "shaftBrand": "True Temper",
   "shaftModel": "Dynamic Gold Mid",
   "length": "Standard",
   "lie": "Standard",
   "setComp": "4-AW (8 clubs)",
   "notes": "",
   "headcover": true,
   "gripCond": "New",
   "grip": "Stock",
   "tradeEligible": false,
   "arrived": "2026-09-05",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2025,
   "stock": 1
  },
  {
   "sku": "PWR-VK-SM10WE-WEDGE-00173",
   "brand": "Vokey",
   "model": "SM10 Wedge",
   "cat": "wedge",
   "club": "Wedge",
   "price": 189,
   "cond": 10,
   "type": "new",
   "dex": "RH/LH",
   "flex": "R/S/X",
   "loft": "46\u00b0\u201362\u00b0",
   "shaftBrand": "True Temper",
   "shaftModel": "Dynamic Gold S200",
   "length": "Standard",
   "lie": "Standard",
   "setComp": null,
   "notes": "All grinds in stock. Custom stamping available.",
   "headcover": true,
   "gripCond": "New",
   "grip": "Stock",
   "tradeEligible": false,
   "arrived": "2026-08-08",
   "find": false,
   "featured": true,
   "compare": null,
   "year": 2025,
   "stock": 4
  },
  {
   "sku": "PWR-CL-RTX6ZI-WEDGE-00174",
   "brand": "Cleveland",
   "model": "RTX 6 ZipCore",
   "cat": "wedge",
   "club": "Wedge",
   "price": 169,
   "cond": 10,
   "type": "new",
   "dex": "RH/LH",
   "flex": "R/S/X",
   "loft": "46\u00b0\u201360\u00b0",
   "shaftBrand": "True Temper",
   "shaftModel": "Dynamic Gold Spinner",
   "length": "Standard",
   "lie": "Standard",
   "setComp": null,
   "notes": "",
   "headcover": true,
   "gripCond": "New",
   "grip": "Stock",
   "tradeEligible": false,
   "arrived": "2026-08-30",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2025,
   "stock": 3
  },
  {
   "sku": "PWR-TM-MG4WED-WEDGE-00175",
   "brand": "TaylorMade",
   "model": "MG4 Wedge",
   "cat": "wedge",
   "club": "Wedge",
   "price": 179,
   "cond": 10,
   "type": "new",
   "dex": "RH/LH",
   "flex": "R/S/X",
   "loft": "46\u00b0\u201360\u00b0",
   "shaftBrand": "True Temper",
   "shaftModel": "Dynamic Gold S200",
   "length": "Standard",
   "lie": "Standard",
   "setComp": null,
   "notes": "",
   "headcover": true,
   "gripCond": "New",
   "grip": "Stock",
   "tradeEligible": false,
   "arrived": "2026-08-31",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2025,
   "stock": 4
  },
  {
   "sku": "PWR-PG-S159WE-WEDGE-00176",
   "brand": "Ping",
   "model": "s159 Wedge",
   "cat": "wedge",
   "club": "Wedge",
   "price": 179,
   "cond": 10,
   "type": "new",
   "dex": "RH/LH",
   "flex": "R/S/X",
   "loft": "46\u00b0\u201362\u00b0",
   "shaftBrand": "Ping",
   "shaftModel": "Z-Z115",
   "length": "Standard",
   "lie": "Standard",
   "setComp": null,
   "notes": "",
   "headcover": true,
   "gripCond": "New",
   "grip": "Stock",
   "tradeEligible": false,
   "arrived": "2026-08-14",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2025,
   "stock": 1
  },
  {
   "sku": "PWR-SC-STUDIO-PUTTER-00177",
   "brand": "Scotty Cameron",
   "model": "Studio Style Newport 2",
   "cat": "putter",
   "club": "Putter",
   "price": 479,
   "cond": 10,
   "type": "new",
   "dex": "RH/LH",
   "flex": "R/S/X",
   "loft": null,
   "shaftBrand": null,
   "shaftModel": null,
   "length": "33\" / 34\" / 35\"",
   "lie": "Standard",
   "setComp": null,
   "notes": "",
   "headcover": true,
   "gripCond": "New",
   "grip": "Pistolini Plus",
   "tradeEligible": false,
   "arrived": "2026-07-29",
   "find": false,
   "featured": true,
   "compare": null,
   "year": 2025,
   "stock": 1
  },
  {
   "sku": "PWR-OD-AIONEC-PUTTER-00178",
   "brand": "Odyssey",
   "model": "Ai-One Cruiser Jailbird",
   "cat": "putter",
   "club": "Putter",
   "price": 329,
   "cond": 10,
   "type": "new",
   "dex": "RH/LH",
   "flex": "R/S/X",
   "loft": null,
   "shaftBrand": null,
   "shaftModel": null,
   "length": "35\" / 38\"",
   "lie": "Standard",
   "setComp": null,
   "notes": "",
   "headcover": true,
   "gripCond": "New",
   "grip": "SuperStroke Traxion",
   "tradeEligible": false,
   "arrived": "2026-07-23",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2025,
   "stock": 5
  },
  {
   "sku": "PWR-PG-PLDMIL-PUTTER-00179",
   "brand": "Ping",
   "model": "PLD Milled Anser",
   "cat": "putter",
   "club": "Putter",
   "price": 449,
   "cond": 10,
   "type": "new",
   "dex": "RH/LH",
   "flex": "R/S/X",
   "loft": null,
   "shaftBrand": null,
   "shaftModel": null,
   "length": "33\"\u201335\"",
   "lie": "Standard",
   "setComp": null,
   "notes": "",
   "headcover": true,
   "gripCond": "New",
   "grip": "PP58",
   "tradeEligible": false,
   "arrived": "2026-08-04",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2025,
   "stock": 3
  },
  {
   "sku": "PWR-TM-SPIDER-PUTTER-00180",
   "brand": "TaylorMade",
   "model": "Spider Tour",
   "cat": "putter",
   "club": "Putter",
   "price": 349,
   "cond": 10,
   "type": "new",
   "dex": "RH/LH",
   "flex": "R/S/X",
   "loft": null,
   "shaftBrand": null,
   "shaftModel": null,
   "length": "34\" / 35\"",
   "lie": "Standard",
   "setComp": null,
   "notes": "",
   "headcover": true,
   "gripCond": "New",
   "grip": "SuperStroke Pistol GT",
   "tradeEligible": false,
   "arrived": "2026-08-19",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2025,
   "stock": 6
  },
  {
   "sku": "PWR-CW-WARBIR-SET-00181",
   "brand": "Callaway",
   "model": "Warbird Complete Set",
   "cat": "set",
   "club": "Set",
   "price": 699,
   "cond": 10,
   "type": "new",
   "dex": "RH/LH",
   "flex": "R/S/X",
   "loft": null,
   "shaftBrand": null,
   "shaftModel": null,
   "length": "Standard",
   "lie": "Standard",
   "setComp": "Driver, 3W, 5H, 6-PW, SW, Putter, Bag",
   "notes": "The set we recommend to every beginner who walks in.",
   "headcover": true,
   "gripCond": "New",
   "grip": "Stock",
   "tradeEligible": false,
   "arrived": "2026-08-18",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2025,
   "stock": 5
  },
  {
   "sku": "PWR-CB-FLYXLC-SET-00182",
   "brand": "Cobra",
   "model": "Fly-XL Complete Set",
   "cat": "set",
   "club": "Set",
   "price": 899,
   "cond": 10,
   "type": "new",
   "dex": "RH/LH",
   "flex": "R/S/X",
   "loft": null,
   "shaftBrand": null,
   "shaftModel": null,
   "length": "Standard",
   "lie": "Standard",
   "setComp": "Driver, 3W, 4H, 5-PW, SW, Putter, Cart Bag",
   "notes": "",
   "headcover": true,
   "gripCond": "New",
   "grip": "Stock",
   "tradeEligible": false,
   "arrived": "2026-08-09",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2025,
   "stock": 5
  },
  {
   "sku": "PWR-FJ-VENTUS-DRIVER-00183",
   "brand": "Fujikura",
   "model": "Ventus Blue (VeloCore+)",
   "cat": "shaft",
   "club": "Driver Shaft",
   "price": 350,
   "cond": 10,
   "type": "new",
   "dex": "RH/LH",
   "flex": "R/S/X",
   "loft": null,
   "shaftBrand": null,
   "shaftModel": null,
   "length": "Standard",
   "lie": "Standard",
   "setComp": null,
   "notes": "Installed and tipped to spec in our shop, $25.",
   "headcover": true,
   "gripCond": "New",
   "grip": "Stock",
   "tradeEligible": false,
   "arrived": "2026-07-20",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2025,
   "stock": 4
  },
  {
   "sku": "PWR-GD-TOURAD-DRIVER-00184",
   "brand": "Graphite Design",
   "model": "Tour AD DI",
   "cat": "shaft",
   "club": "Driver Shaft",
   "price": 400,
   "cond": 10,
   "type": "new",
   "dex": "RH/LH",
   "flex": "S/X",
   "loft": null,
   "shaftBrand": null,
   "shaftModel": null,
   "length": "Standard",
   "lie": "Standard",
   "setComp": null,
   "notes": "",
   "headcover": true,
   "gripCond": "New",
   "grip": "Stock",
   "tradeEligible": false,
   "arrived": "2026-09-05",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2025,
   "stock": 1
  },
  {
   "sku": "PWR-PX-HZRDUS-DRIVER-00185",
   "brand": "Project X",
   "model": "HZRDUS Black Gen4",
   "cat": "shaft",
   "club": "Driver Shaft",
   "price": 230,
   "cond": 10,
   "type": "new",
   "dex": "RH/LH",
   "flex": "6.0/6.5",
   "loft": null,
   "shaftBrand": null,
   "shaftModel": null,
   "length": "Standard",
   "lie": "Standard",
   "setComp": null,
   "notes": "",
   "headcover": true,
   "gripCond": "New",
   "grip": "Stock",
   "tradeEligible": false,
   "arrived": "2026-07-11",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2025,
   "stock": 3
  },
  {
   "sku": "PWR-MC-TENSEI-DRIVER-00186",
   "brand": "Mitsubishi",
   "model": "Tensei 1K Pro White",
   "cat": "shaft",
   "club": "Driver Shaft",
   "price": 300,
   "cond": 10,
   "type": "new",
   "dex": "RH/LH",
   "flex": "S/X",
   "loft": null,
   "shaftBrand": null,
   "shaftModel": null,
   "length": "Standard",
   "lie": "Standard",
   "setComp": null,
   "notes": "",
   "headcover": true,
   "gripCond": "New",
   "grip": "Stock",
   "tradeEligible": false,
   "arrived": "2026-08-10",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2025,
   "stock": 6
  },
  {
   "sku": "PWR-KB-TOUR12-IRONSH-00187",
   "brand": "KBS",
   "model": "Tour 120 (per shaft)",
   "cat": "shaft",
   "club": "Iron Shaft",
   "price": 42,
   "cond": 10,
   "type": "new",
   "dex": "RH/LH",
   "flex": "S/X",
   "loft": null,
   "shaftBrand": null,
   "shaftModel": null,
   "length": "Standard",
   "lie": "Standard",
   "setComp": null,
   "notes": "",
   "headcover": true,
   "gripCond": "New",
   "grip": "Stock",
   "tradeEligible": false,
   "arrived": "2026-07-29",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2025,
   "stock": 1
  },
  {
   "sku": "PWR-TT-DYNAMI-IRONSH-00188",
   "brand": "True Temper",
   "model": "Dynamic Gold 120 (per shaft)",
   "cat": "shaft",
   "club": "Iron Shaft",
   "price": 34,
   "cond": 10,
   "type": "new",
   "dex": "RH/LH",
   "flex": "S300/X100",
   "loft": null,
   "shaftBrand": null,
   "shaftModel": null,
   "length": "Standard",
   "lie": "Standard",
   "setComp": null,
   "notes": "",
   "headcover": true,
   "gripCond": "New",
   "grip": "Stock",
   "tradeEligible": false,
   "arrived": "2026-09-06",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2025,
   "stock": 6
  },
  {
   "sku": "PWR-NP-MODUS3-IRONSH-00189",
   "brand": "Nippon",
   "model": "Modus3 Tour 105 (per shaft)",
   "cat": "shaft",
   "club": "Iron Shaft",
   "price": 45,
   "cond": 10,
   "type": "new",
   "dex": "RH/LH",
   "flex": "R/S/X",
   "loft": null,
   "shaftBrand": null,
   "shaftModel": null,
   "length": "Standard",
   "lie": "Standard",
   "setComp": null,
   "notes": "",
   "headcover": true,
   "gripCond": "New",
   "grip": "Stock",
   "tradeEligible": false,
   "arrived": "2026-07-27",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2025,
   "stock": 3
  },
  {
   "sku": "PWR-GP-MCCPLU-GRIP-00190",
   "brand": "Golf Pride",
   "model": "MCC Plus4",
   "cat": "grip",
   "club": "Grip",
   "price": 14.99,
   "cond": 10,
   "type": "new",
   "dex": "RH/LH",
   "flex": "\u2014",
   "loft": null,
   "shaftBrand": null,
   "shaftModel": null,
   "length": "Standard",
   "lie": "Standard",
   "setComp": null,
   "notes": "Installed free with purchase of 8 or more.",
   "headcover": true,
   "gripCond": "New",
   "grip": "Stock",
   "tradeEligible": false,
   "arrived": "2026-07-30",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2025,
   "stock": 48
  },
  {
   "sku": "PWR-GP-TOURVE-GRIP-00191",
   "brand": "Golf Pride",
   "model": "Tour Velvet 360",
   "cat": "grip",
   "club": "Grip",
   "price": 9.99,
   "cond": 10,
   "type": "new",
   "dex": "RH/LH",
   "flex": "\u2014",
   "loft": null,
   "shaftBrand": null,
   "shaftModel": null,
   "length": "Standard",
   "lie": "Standard",
   "setComp": null,
   "notes": "",
   "headcover": true,
   "gripCond": "New",
   "grip": "Stock",
   "tradeEligible": false,
   "arrived": "2026-07-28",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2025,
   "stock": 60
  },
  {
   "sku": "PWR-GP-CP2PRO-GRIP-00192",
   "brand": "Golf Pride",
   "model": "CP2 Pro",
   "cat": "grip",
   "club": "Grip",
   "price": 12.99,
   "cond": 10,
   "type": "new",
   "dex": "RH/LH",
   "flex": "\u2014",
   "loft": null,
   "shaftBrand": null,
   "shaftModel": null,
   "length": "Standard",
   "lie": "Standard",
   "setComp": null,
   "notes": "",
   "headcover": true,
   "gripCond": "New",
   "grip": "Stock",
   "tradeEligible": false,
   "arrived": "2026-08-22",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2025,
   "stock": 30
  },
  {
   "sku": "PWR-LK-CROSSL-GRIP-00193",
   "brand": "Lamkin",
   "model": "Crossline",
   "cat": "grip",
   "club": "Grip",
   "price": 8.99,
   "cond": 10,
   "type": "new",
   "dex": "RH/LH",
   "flex": "\u2014",
   "loft": null,
   "shaftBrand": null,
   "shaftModel": null,
   "length": "Standard",
   "lie": "Standard",
   "setComp": null,
   "notes": "",
   "headcover": true,
   "gripCond": "New",
   "grip": "Stock",
   "tradeEligible": false,
   "arrived": "2026-08-16",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2025,
   "stock": 40
  },
  {
   "sku": "PWR-SS-ZENERG-PUTTER-00194",
   "brand": "SuperStroke",
   "model": "Zenergy Pistol 2.0",
   "cat": "grip",
   "club": "Putter Grip",
   "price": 34.99,
   "cond": 10,
   "type": "new",
   "dex": "RH/LH",
   "flex": "\u2014",
   "loft": null,
   "shaftBrand": null,
   "shaftModel": null,
   "length": "Standard",
   "lie": "Standard",
   "setComp": null,
   "notes": "",
   "headcover": true,
   "gripCond": "New",
   "grip": "Stock",
   "tradeEligible": false,
   "arrived": "2026-08-18",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2025,
   "stock": 12
  },
  {
   "sku": "PWR-TI-PROV1D-GOLFBA-00195",
   "brand": "Titleist",
   "model": "Pro V1 (dozen)",
   "cat": "ball",
   "club": "Golf Balls",
   "price": 54.99,
   "cond": 10,
   "type": "new",
   "dex": "RH/LH",
   "flex": "\u2014",
   "loft": null,
   "shaftBrand": null,
   "shaftModel": null,
   "length": "Standard",
   "lie": "Standard",
   "setComp": null,
   "notes": "",
   "headcover": true,
   "gripCond": "New",
   "grip": "Stock",
   "tradeEligible": false,
   "arrived": "2026-07-11",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2025,
   "stock": 24
  },
  {
   "sku": "PWR-TI-PROV1X-GOLFBA-00196",
   "brand": "Titleist",
   "model": "Pro V1x (dozen)",
   "cat": "ball",
   "club": "Golf Balls",
   "price": 54.99,
   "cond": 10,
   "type": "new",
   "dex": "RH/LH",
   "flex": "\u2014",
   "loft": null,
   "shaftBrand": null,
   "shaftModel": null,
   "length": "Standard",
   "lie": "Standard",
   "setComp": null,
   "notes": "",
   "headcover": true,
   "gripCond": "New",
   "grip": "Stock",
   "tradeEligible": false,
   "arrived": "2026-08-18",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2025,
   "stock": 20
  },
  {
   "sku": "PWR-TM-TP5DOZ-GOLFBA-00197",
   "brand": "TaylorMade",
   "model": "TP5 (dozen)",
   "cat": "ball",
   "club": "Golf Balls",
   "price": 49.99,
   "cond": 10,
   "type": "new",
   "dex": "RH/LH",
   "flex": "\u2014",
   "loft": null,
   "shaftBrand": null,
   "shaftModel": null,
   "length": "Standard",
   "lie": "Standard",
   "setComp": null,
   "notes": "",
   "headcover": true,
   "gripCond": "New",
   "grip": "Stock",
   "tradeEligible": false,
   "arrived": "2026-08-01",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2025,
   "stock": 15
  },
  {
   "sku": "PWR-SX-ZSTARD-GOLFBA-00198",
   "brand": "Srixon",
   "model": "Z-Star (dozen)",
   "cat": "ball",
   "club": "Golf Balls",
   "price": 44.99,
   "cond": 10,
   "type": "new",
   "dex": "RH/LH",
   "flex": "\u2014",
   "loft": null,
   "shaftBrand": null,
   "shaftModel": null,
   "length": "Standard",
   "lie": "Standard",
   "setComp": null,
   "notes": "",
   "headcover": true,
   "gripCond": "New",
   "grip": "Stock",
   "tradeEligible": false,
   "arrived": "2026-08-09",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2025,
   "stock": 15
  },
  {
   "sku": "PWR-BS-TOURBR-GOLFBA-00199",
   "brand": "Bridgestone",
   "model": "Tour B RX (dozen)",
   "cat": "ball",
   "club": "Golf Balls",
   "price": 47.99,
   "cond": 10,
   "type": "new",
   "dex": "RH/LH",
   "flex": "\u2014",
   "loft": null,
   "shaftBrand": null,
   "shaftModel": null,
   "length": "Standard",
   "lie": "Standard",
   "setComp": null,
   "notes": "",
   "headcover": true,
   "gripCond": "New",
   "grip": "Stock",
   "tradeEligible": false,
   "arrived": "2026-08-27",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2025,
   "stock": 10
  },
  {
   "sku": "PWR-VS-PLAYER-STANDB-00200",
   "brand": "Vessel",
   "model": "Player IV Stand Bag",
   "cat": "bag",
   "club": "Stand Bag",
   "price": 345,
   "cond": 10,
   "type": "new",
   "dex": "RH/LH",
   "flex": "\u2014",
   "loft": null,
   "shaftBrand": null,
   "shaftModel": null,
   "length": "Standard",
   "lie": "Standard",
   "setComp": null,
   "notes": "",
   "headcover": true,
   "gripCond": "New",
   "grip": "Stock",
   "tradeEligible": false,
   "arrived": "2026-09-01",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2025,
   "stock": 6
  },
  {
   "sku": "PWR-TI-PLAYER-STANDB-00201",
   "brand": "Titleist",
   "model": "Players 4 Stand Bag",
   "cat": "bag",
   "club": "Stand Bag",
   "price": 245,
   "cond": 10,
   "type": "new",
   "dex": "RH/LH",
   "flex": "\u2014",
   "loft": null,
   "shaftBrand": null,
   "shaftModel": null,
   "length": "Standard",
   "lie": "Standard",
   "setComp": null,
   "notes": "",
   "headcover": true,
   "gripCond": "New",
   "grip": "Stock",
   "tradeEligible": false,
   "arrived": "2026-08-25",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2025,
   "stock": 4
  },
  {
   "sku": "PWR-PG-HOOFER-STANDB-00202",
   "brand": "Ping",
   "model": "Hoofer 14",
   "cat": "bag",
   "club": "Stand Bag",
   "price": 279,
   "cond": 10,
   "type": "new",
   "dex": "RH/LH",
   "flex": "\u2014",
   "loft": null,
   "shaftBrand": null,
   "shaftModel": null,
   "length": "Standard",
   "lie": "Standard",
   "setComp": null,
   "notes": "",
   "headcover": true,
   "gripCond": "New",
   "grip": "Stock",
   "tradeEligible": false,
   "arrived": "2026-08-15",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2025,
   "stock": 4
  },
  {
   "sku": "PWR-SM-C130CA-CARTBA-00203",
   "brand": "Sun Mountain",
   "model": "C-130 Cart Bag",
   "cat": "bag",
   "club": "Cart Bag",
   "price": 299,
   "cond": 10,
   "type": "new",
   "dex": "RH/LH",
   "flex": "\u2014",
   "loft": null,
   "shaftBrand": null,
   "shaftModel": null,
   "length": "Standard",
   "lie": "Standard",
   "setComp": null,
   "notes": "",
   "headcover": true,
   "gripCond": "New",
   "grip": "Stock",
   "tradeEligible": false,
   "arrived": "2026-09-04",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2025,
   "stock": 2
  },
  {
   "sku": "PWR-FJ-PURETO-GLOVE-00204",
   "brand": "FootJoy",
   "model": "Pure Touch Glove",
   "cat": "glove",
   "club": "Glove",
   "price": 29.99,
   "cond": 10,
   "type": "new",
   "dex": "LH / RH (cadet too)",
   "flex": "\u2014",
   "loft": null,
   "shaftBrand": null,
   "shaftModel": null,
   "length": "Standard",
   "lie": "Standard",
   "setComp": null,
   "notes": "",
   "headcover": true,
   "gripCond": "New",
   "grip": "Stock",
   "tradeEligible": false,
   "arrived": "2026-08-12",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2025,
   "stock": 30
  },
  {
   "sku": "PWR-TI-PLAYER-GLOVE-00205",
   "brand": "Titleist",
   "model": "Players Glove",
   "cat": "glove",
   "club": "Glove",
   "price": 26.99,
   "cond": 10,
   "type": "new",
   "dex": "LH / RH",
   "flex": "\u2014",
   "loft": null,
   "shaftBrand": null,
   "shaftModel": null,
   "length": "Standard",
   "lie": "Standard",
   "setComp": null,
   "notes": "",
   "headcover": true,
   "gripCond": "New",
   "grip": "Stock",
   "tradeEligible": false,
   "arrived": "2026-08-05",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2025,
   "stock": 30
  },
  {
   "sku": "PWR-BN-TOURV6-RANGEF-00206",
   "brand": "Bushnell",
   "model": "Tour V6 Shift",
   "cat": "accessory",
   "club": "Rangefinder",
   "price": 399,
   "cond": 10,
   "type": "new",
   "dex": "RH/LH",
   "flex": "\u2014",
   "loft": null,
   "shaftBrand": null,
   "shaftModel": null,
   "length": "Standard",
   "lie": "Standard",
   "setComp": null,
   "notes": "",
   "headcover": true,
   "gripCond": "New",
   "grip": "Stock",
   "tradeEligible": false,
   "arrived": "2026-07-15",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2025,
   "stock": 2
  },
  {
   "sku": "PWR-GM-APPROA-GPSWAT-00207",
   "brand": "Garmin",
   "model": "Approach S70",
   "cat": "accessory",
   "club": "GPS Watch",
   "price": 649,
   "cond": 10,
   "type": "new",
   "dex": "RH/LH",
   "flex": "\u2014",
   "loft": null,
   "shaftBrand": null,
   "shaftModel": null,
   "length": "Standard",
   "lie": "Standard",
   "setComp": null,
   "notes": "",
   "headcover": true,
   "gripCond": "New",
   "grip": "Stock",
   "tradeEligible": false,
   "arrived": "2026-07-19",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2025,
   "stock": 4
  },
  {
   "sku": "PWR-PW-TOWELD-ACCESS-00208",
   "brand": "PWR Golf Co.",
   "model": "Towel + Divot Tool Kit",
   "cat": "accessory",
   "club": "Accessory",
   "price": 24.99,
   "cond": 10,
   "type": "new",
   "dex": "RH/LH",
   "flex": "\u2014",
   "loft": null,
   "shaftBrand": null,
   "shaftModel": null,
   "length": "Standard",
   "lie": "Standard",
   "setComp": null,
   "notes": "Jaguar embroidered. Yes, really.",
   "headcover": true,
   "gripCond": "New",
   "grip": "Stock",
   "tradeEligible": false,
   "arrived": "2026-07-16",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2025,
   "stock": 40
  },
  {
   "sku": "PWR-PW-SHOPTE-TEE-00209",
   "brand": "PWR Golf Co.",
   "model": "Shop Tee",
   "cat": "apparel",
   "club": "Tee",
   "price": 28,
   "cond": 10,
   "type": "new",
   "dex": "S\u2013XXL",
   "flex": "\u2014",
   "loft": null,
   "shaftBrand": null,
   "shaftModel": null,
   "length": "Standard",
   "lie": "Standard",
   "setComp": null,
   "notes": "Heavyweight black tee, jaguar mark on the back.",
   "headcover": true,
   "gripCond": "New",
   "grip": "Stock",
   "tradeEligible": false,
   "arrived": "2026-08-23",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2025,
   "stock": 40
  },
  {
   "sku": "PWR-PW-WORKBE-HAT-00210",
   "brand": "PWR Golf Co.",
   "model": "Workbench Hat",
   "cat": "apparel",
   "club": "Hat",
   "price": 32,
   "cond": 10,
   "type": "new",
   "dex": "OS",
   "flex": "\u2014",
   "loft": null,
   "shaftBrand": null,
   "shaftModel": null,
   "length": "Standard",
   "lie": "Standard",
   "setComp": null,
   "notes": "",
   "headcover": true,
   "gripCond": "New",
   "grip": "Stock",
   "tradeEligible": false,
   "arrived": "2026-08-14",
   "find": false,
   "featured": false,
   "compare": null,
   "year": 2025,
   "stock": 25
  }
 ]
};
